### ISSUE TITLE
compressed css breaks html highlighting 

### ISSUE THREAD

**Issue by diego-vieira** [Microsoft/vscode-html-languageservice#11] opened 2017-04-28 14:51 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: None

---

Steps to Reproduce:

1. Save the example at https://www.ampproject.org/docs/tutorials/create/basic_markup as an HTML file
2. Check the markup is not highlighted after the ``` @-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}} ```

![screen shot 2017-04-28 at 15 49 45](https://cloud.githubusercontent.com/assets/930792/25534005/65b65914-2c2a-11e7-8d1f-3fa7bd51f7bc.jpg)

If you add a space after the ``}}`` it works.
![screen shot 2017-04-28 at 15 49 55](https://cloud.githubusercontent.com/assets/930792/25534004/65b576e8-2c2a-11e7-80de-6ad8eba82f67.jpg)

**Comment by aeschli** [comment] 2017-05-29 14:42
Syntax highlighting is based on the text mate grammar from https://github.com/textmate/html.tmbundle.

But it looks the issue is fixed in the latest insiders:
![image](https://cloud.githubusercontent.com/assets/6461412/26553867/cb2137bc-448d-11e7-82d1-e23872a9084f.png)

**Closed by aeschli** 2017-05-29 14:42 UTC
