### ISSUE TITLE
HTML formater puts new line after open brace and open tag.

### ISSUE THREAD

**Issue by motz-art** [Microsoft/vscode-html-languageservice#27] opened 2018-06-19 08:38 UTC
- VSCode Version: 1.24.1, 1.25.0-insider
- OS Version: Windows 10 pro 

Steps to Reproduce:

1. Create .html file. Add next line:
```
This (<span>is</span>) text.
```
2. Run `Format Document` or press CTRL+Shift+F.

Expected Result:
Line remains unchanged:
```
This (<span>is</span>) text.
```

Actual Result:
Formater puts new line after open brace and open tag:
```
This (
<span>is</span>) text.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2018-08-06 19:25
duplicate of https://github.com/beautify-web/js-beautify/issues/841

**Closed by aeschli** 2018-08-06 19:25 UTC
