### ISSUE TITLE
Dynamic custom data based code in a workspace

### ISSUE THREAD

**Issue by rictic** [microsoft/vscode-html-languageservice#50] opened 2019-02-07 22:18 UTC
Looking at https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md

I may be misreading/misunderstanding, but it looks like the ways to provide custom data are all static?

A couple of use cases:
  - A user's code has dependencies that declare custom elements. Suppose that these dependencies ship with html custom data json files (e.g. in well known locations within the node_modules directory). Would the user need to manually set the `html.experimental.customData` array to point to the paths to these files?

  - A user's own code may declare custom elements. If an extension performs real time static analysis on that code, can it contribute information about those custom elements to the html languageservice?

**Comment by aeschli** [comment] 2019-02-08 08:39
Yes, the feature we have added allows to contribute static custom data.
If your code has dependencies to libraries that declare custom elements, we hope that these libraries will publish a extension that defines these elements. 

To provide data dynamically you would have to use the good old vscode providers (completion provider, hover provider). That requires you to analyse the HTML resp CSS yourself (for which we provide node libraries). Likely you need to do that anyway as you need more context and code understanding. You'll be better off being a full blown, self-contained language server, with full control over the user experience on files of your language.

**Comment by aeschli** [comment] 2019-02-08 08:48
Oh, I just realised that you filed this against the html-languageservice. There (in the current, not yet finalised API) API clients provide a `IHTMLDataProvider` that is not necessarily static. It will be asked every time information is needed (on code complete, hover...).

**Comment by octref** [comment] 2019-02-08 17:08
> the ways to provide custom data are all static

That's correct. We'll look into dynamic custom data. Static custom data is more for library authors.

> * A user's code has dependencies that declare custom elements. Suppose that these dependencies ship with html custom data json files (e.g. in well known locations within the node_modules directory). Would the user need to manually set the `html.experimental.customData` array to point to the paths to these files?

For now the user has to specify the paths. In the future we might read `node_modules`. I'm doing it for Vue (https://github.com/quasarframework/quasar/blob/dev/quasar/package.json#L108-L110) already but I don't think for HTML / VS Code it would come as easily. The data format is nowhere as formalized / adopted as `d.ts` files.

**Comment by rictic** [comment] 2019-02-08 23:13
> To provide data dynamically you would have to use the good old vscode providers (completion provider, hover provider). That requires you to analyse the HTML resp CSS yourself (for which we provide node libraries). Likely you need to do that anyway as you need more context and code understanding. You'll be better off being a full blown, self-contained language server, with full control over the user experience on files of your language.

That's [what we do today](https://github.com/Polymer/tools/tree/master/packages/editor-service), but I'm excited to get this functionality folded into the vscode-html-languageservice, as custom elements are a standard part of the HTML spec.

> For now the user has to specify the paths. In the future we might read `node_modules`. I'm doing it for Vue (https://github.com/quasarframework/quasar/blob/dev/quasar/package.json#L108-L110) already but I don't think for HTML / VS Code it would come as easily.

> Static custom data is more for library authors.

For custom elements codebases it's often the case that a user will have many small dependencies, each of which may declare zero or more custom elements. That makes any static of configuration based solution challenging.

> API clients provide a `IHTMLDataProvider` that is not necessarily static. It will be asked every time information is needed (on code complete, hover...).

That sounds promising!

I also understand that this work is still early, and starting with static data is a super reasonable first step :)

**Comment by aeschli** [comment] 2019-10-14 11:13
Closing. The customDataProviders are not static by design.

**Closed by aeschli** 2019-10-14 11:13 UTC
Labels: feature-request
